-- ============================================================================
-- MyComplaintPortal — Oracle Database DDL Schema Script (ojdbc11 compatible)
-- Supports Oracle 12c, 19c, 21c, and 23c Databases
-- Relational Schemas for Users, Auth, Complaints, Departments, Admins & Logs
-- ============================================================================

-- 1. AUTHENTICATION & USERS TABLE
CREATE TABLE USERS_AUTH (
    USER_ID VARCHAR2(64) PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL,
    EMAIL VARCHAR2(128) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(256) NOT NULL,
    PHONE VARCHAR2(32),
    LOCATION VARCHAR2(256),
    ROLE VARCHAR2(32) DEFAULT 'CITIZEN' NOT NULL,
    IS_BLOCKED NUMBER(1) DEFAULT 0 NOT NULL,
    EMAIL_VERIFIED NUMBER(1) DEFAULT 0 NOT NULL,
    PROFILE_IMAGE_URL VARCHAR2(512),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. MUNICIPAL DEPARTMENTS TABLE
CREATE TABLE MUNICIPAL_DEPARTMENTS (
    DEPT_ID VARCHAR2(64) PRIMARY KEY,
    DEPT_NAME VARCHAR2(128) NOT NULL,
    DEPT_CODE VARCHAR2(32) UNIQUE NOT NULL,
    OFFICIAL_EMAIL VARCHAR2(128) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    TOTAL_COUNT NUMBER(10) DEFAULT 0,
    SOLVED_COUNT NUMBER(10) DEFAULT 0,
    PENDING_COUNT NUMBER(10) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. ADMIN ACCOUNTS TABLE
CREATE TABLE ADMIN_ACCOUNTS (
    ADMIN_ID VARCHAR2(64) PRIMARY KEY,
    USERNAME VARCHAR2(128) NOT NULL,
    EMAIL VARCHAR2(128) UNIQUE NOT NULL,
    GRANT_LEVEL VARCHAR2(64) DEFAULT 'Department Admin' NOT NULL,
    DESIGNATION VARCHAR2(128),
    BADGE_ID VARCHAR2(64),
    DEPT_ID VARCHAR2(64),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ADMIN_DEPT FOREIGN KEY (DEPT_ID) REFERENCES MUNICIPAL_DEPARTMENTS(DEPT_ID) ON DELETE SET NULL
);

-- 4. COMPLAINTS MAIN TABLE
CREATE TABLE COMPLAINTS (
    COMPLAINT_ID VARCHAR2(64) PRIMARY KEY,
    TITLE VARCHAR2(256) NOT NULL,
    DESCRIPTION CLOB NOT NULL,
    PINCODE VARCHAR2(16) NOT NULL,
    LOCATION_NAME VARCHAR2(256) NOT NULL,
    DEPT_ID VARCHAR2(64),
    DEPT_NAME VARCHAR2(128),
    STATUS VARCHAR2(32) DEFAULT 'CREATED' NOT NULL,
    UPVOTES NUMBER(10) DEFAULT 0 NOT NULL,
    REPOSTS NUMBER(10) DEFAULT 0 NOT NULL,
    IS_REPORTED NUMBER(1) DEFAULT 0 NOT NULL,
    REPORT_COUNT NUMBER(10) DEFAULT 0,
    USER_ID VARCHAR2(64) NOT NULL,
    USER_NAME VARCHAR2(128) NOT NULL,
    TRACKING_TOKEN VARCHAR2(128) UNIQUE,
    PROOF_IMAGE_ID VARCHAR2(128),
    OFFICER_NOTES CLOB,
    WAS_REDIRECTED NUMBER(1) DEFAULT 0,
    REDIRECTED_FROM_DEPT VARCHAR2(128),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    RESOLVED_AT TIMESTAMP,
    CONSTRAINT FK_COMPLAINT_USER FOREIGN KEY (USER_ID) REFERENCES USERS_AUTH(USER_ID),
    CONSTRAINT FK_COMPLAINT_DEPT FOREIGN KEY (DEPT_ID) REFERENCES MUNICIPAL_DEPARTMENTS(DEPT_ID) ON DELETE SET NULL
);

-- 5. COMPLAINT TIMELINE LOGS TABLE
CREATE TABLE COMPLAINT_TIMELINE (
    TIMELINE_ID VARCHAR2(64) PRIMARY KEY,
    COMPLAINT_ID VARCHAR2(64) NOT NULL,
    STAGE_TITLE VARCHAR2(128) NOT NULL,
    STAGE_DATE VARCHAR2(64) NOT NULL,
    STATUS_FLAG VARCHAR2(32) NOT NULL, -- 'done', 'current', 'pending'
    CONSTRAINT FK_TIMELINE_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(COMPLAINT_ID) ON DELETE CASCADE
);

-- 6. COMPLAINT ATTACHMENTS (MONGODB GRIDFS REFERENCE METADATA)
CREATE TABLE COMPLAINT_ATTACHMENTS (
    ATTACHMENT_ID VARCHAR2(64) PRIMARY KEY,
    COMPLAINT_ID VARCHAR2(64) NOT NULL,
    GRIDFS_IMAGE_ID VARCHAR2(128) NOT NULL,
    FILE_NAME VARCHAR2(256),
    CONTENT_TYPE VARCHAR2(64),
    CONSTRAINT FK_ATTACH_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(COMPLAINT_ID) ON DELETE CASCADE
);

-- 7. COMPLAINT FEEDBACK TABLE
CREATE TABLE COMPLAINT_FEEDBACK (
    FEEDBACK_ID VARCHAR2(64) PRIMARY KEY,
    COMPLAINT_ID VARCHAR2(64) UNIQUE NOT NULL,
    RATING NUMBER(2) NOT NULL,
    COMMENT_TEXT VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_FEEDBACK_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(COMPLAINT_ID) ON DELETE CASCADE
);

-- 8. EMAIL LOGS TABLE
CREATE TABLE EMAIL_LOGS (
    LOG_ID VARCHAR2(64) PRIMARY KEY,
    RECIPIENT_EMAIL VARCHAR2(128) NOT NULL,
    SUBJECT VARCHAR2(256) NOT NULL,
    EMAIL_TYPE VARCHAR2(64) NOT NULL, -- 'OFFICER_NOTIFICATION', 'CITIZEN_SOLVED', 'OTP_VERIFICATION'
    STATUS VARCHAR2(32) NOT NULL,
    SENT_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 9. AI CLASSIFICATION LOGS TABLE
CREATE TABLE AI_CLASSIFICATION_LOGS (
    LOG_ID VARCHAR2(64) PRIMARY KEY,
    COMPLAINT_ID VARCHAR2(64),
    INPUT_DESCRIPTION CLOB,
    DETECTED_PROBLEM VARCHAR2(128),
    RECOMMENDED_DEPT VARCHAR2(128),
    MISMATCH_DETECTED NUMBER(1) DEFAULT 0,
    MISMATCH_REASON VARCHAR2(512),
    CONFIDENCE_SCORE NUMBER(5,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ============================================================================
-- INITIAL SEED DATA FOR ORACLE DATABASE
-- ============================================================================

-- Seed Super Admin Account (BCrypt hash for 'ksjaisurya')
INSERT INTO USERS_AUTH (USER_ID, NAME, EMAIL, PASSWORD_HASH, ROLE, IS_BLOCKED, EMAIL_VERIFIED)
VALUES (
    'usr-superadmin', 
    'Super Admin Jai Surya', 
    'jaisurya7482@gmail.com', 
    '$2a$10$e8wFvV4qj4U74N5gPZ8j/uL2bE2iZ9eZ6bY7bX6v8b9c0d1e2f3g4', -- BCrypt for 'ksjaisurya'
    'SUPER_ADMIN', 
    0, 
    1
);

-- Seed Municipal Departments
INSERT INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-pwd', 'Public Works Department (PWD)', 'DEPT-01', 'b.karthikeyan10000@gmail.com', 'Road maintenance, bridges, drainage and civic infrastructure.', 420, 378, 42);

INSERT INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-eb', 'Electricity Board (EB)', 'DEPT-02', 'eb@coimbatore.gov.in', 'Streetlight outages, transformer repairs, power grid management.', 380, 357, 23);

INSERT INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-sanitation', 'Sanitation & Solid Waste Dept', 'DEPT-03', 'b.karthikeyan10000@gmail.com    ', 'Garbage collection, waste dumping, public hygiene.', 510, 464, 46);

INSERT INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-water', 'Water Supply & Sewage Board', 'DEPT-04', 'water@coimbatore.gov.in', 'Pipeline leaks, sewage overflow, drinking water supply.', 290, 249, 41);

INSERT INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-transport', 'Transport & Traffic Division', 'DEPT-05', 'transport@coimbatore.gov.in', 'Traffic signals, bus shelter repair, road safety signs.', 180, 158, 22);

INSERT INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-it', 'IT & Smart Governance Services', 'DEPT-06', 'it@coimbatore.gov.in', 'Digital portal services, CCTV monitoring, smart city tech.', 120, 115, 5);

COMMIT;
